# Randomness and Random seeding

In [1]:
# import libraries
import numpy as np
import torch

In [2]:
# generate a completely random number
np.random.randn(5)

array([ 0.24725547, -0.85090106,  0.1977962 ,  0.71032157,  2.47880284])

In [5]:
# make the reproducable by using seeding

np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

# The values will be
# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


**Note** `np.random.seed()` is the old mechanism for numpy. Numpy has a newer mechanism that allows the usage of multiple seeds at once.

## New seed mechanism in Numpy

In [18]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print( randseed1.randn(5) ) # same sequence
print( randseed2.randn(5) ) # different from above, but same each time
print( randseed1.randn(5) ) # same as two up
print( randseed2.randn(5) ) # same as two up
print( np.random.randn(5) ) # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[-0.835944   -0.00369604  0.39309468  0.68449508  0.77520168]


## Pytorch

Pytorch uses the same method as old numpy seeding.

In [24]:
torch.randn(5)

tensor([-0.7929, -0.1994, -0.2303,  0.7805,  1.0563])

In [28]:
torch.manual_seed(17)
print(torch.randn(5))

# torch's seed doesn't spread to numpy
print(np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[-0.97693692  0.4680703   2.87112692 -1.20808568  1.00360318]
