# Math numpy and Pytorch

In [1]:
# import libraries
import numpy as np
import torch

## Using numpy

In [9]:
# Create a vector
nv = np.array([[1,2,3,4]])
print(nv), print()

# transpose it
print(nv.T)

[[1 2 3 4]]

[[1]
 [2]
 [3]
 [4]]


Notice how we used double `[]` like `[[]]`.

This is **important!**

In [6]:
print(f'Single bracket shape: {np.array([1,2,3,4]).shape}')
print(f'Double bracket shape: {np.array([[1,2,3,4]]).shape}')

Single bracket shape: (4,)
Double bracket shape: (1, 4)


Double bracket produces far less issues generally.
- `[]` indicates this is "4 columns with no rows" 
- `[[]]` indicate this is a "single row with 4 columns".

In [10]:
# repeat for matrix
nm = np.array([[1,2,3,4], [4,5,6,7]])
print(nm), print()

# transpose it
print(nm.T)

[[1 2 3 4]
 [4 5 6 7]]

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


## Using pytorch

In [11]:
# create a vector
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print()

# transpose it
print(tv.T)

tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])


In [12]:
# repeat for matrix
tm = torch.tensor([[1,2,3,4], [4,5,6,7]])
print(tm), print()

# transpose it
print(tm.T)

tensor([[1, 2, 3, 4],
        [4, 5, 6, 7]])

tensor([[1, 4],
        [2, 5],
        [3, 6],
        [4, 7]])


Examing the types

In [13]:
# Examine types

print(type(nv))
print(type(nm))
print(type(tv))
print(type(tm))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
