# Matrix Multiplication (Dot Product)

In [1]:
# import libraries
import numpy as np
import torch

## Using numpy

In [5]:
# create random matrix
A = np.random.randn(3,4)
B = np.random.randn(4,5)

print(A @ B) # result shape (3,5)

[[ 1.4592243  -1.25557792  0.01036048 -0.20977724  1.78057493]
 [ 0.29411493 -1.58815565 -0.40720063 -0.10464838  0.90501063]
 [-0.234163    2.17448334  1.26815157  1.52289162 -2.52546414]]


## Using pytorch

In [6]:
# create random matrix
A = torch.randn(3,4)
B = torch.randn(4,5)

# Alternative way to make random matrix. np.ndarray -> tensor
C = np.random.randn(4,7)
C = torch.tensor(C, dtype=torch.float)

print(A@B) # result shape (3,5)
print(A@C) # result shape (3,7)

tensor([[ 0.4944, -0.0834, -0.1990, -2.8046, -1.2898],
        [-0.9485,  0.9469,  1.8657,  2.7844, -0.3810],
        [ 1.1780, -1.8808, -0.6951,  0.4957, -0.2256]])
tensor([[ 0.2369, -0.4986,  1.5668, -1.0001, -0.8889, -1.1818,  0.8018],
        [ 0.2937,  1.0205, -1.2993, -0.4269, -1.1934,  2.3227, -1.0015],
        [ 0.4162,  0.0441, -1.4305, -0.2116,  2.5480, -0.4778,  0.3650]])
