# Matrix Multiplication (Dot Product)

In [1]:
# import libraries
import numpy as np
import torch

## Using numpy

In [2]:
# create random matrix
A = np.random.randn(3,4)
B = np.random.randn(4,5)

print(A @ B) # result shape (3,5)

[[ 0.47611978  0.98527017  2.15387259  1.39369689 -0.23690873]
 [ 1.29897513  1.10483543  2.91240902  1.38512826  0.26314271]
 [-2.09144699 -2.08383143 -2.49781723 -4.77028088  0.11788112]]


## Using pytorch

In [4]:
# create random matrix
A = torch.randn(3,4)
B = torch.randn(4,5)

# Alternative way to make random matrix. np.ndarray -> tensor
C = np.random.randn(4,7)
C = torch.tensor(C, dtype=torch.float)

print(A@B) # result shape (3,5)
print(A@C) # result shape (3,7)

tensor([[ 1.0099, -3.6572, -4.1545,  0.9367,  1.8187],
        [-3.1711, -1.5280,  0.5644,  4.0732, -2.5985],
        [-0.9393,  0.5288,  1.3743,  0.2248, -0.6772]])
tensor([[ 1.7768, -2.1300, -1.6710, -2.3467, -3.3523, -0.3172, -0.9086],
        [ 0.9750,  0.9488,  0.1408,  0.9291, -2.7883, -3.5846, -1.7211],
        [-0.0281,  0.1801,  0.5480,  0.8477,  0.9355, -0.2733, -0.3576]])
